# Generated by Django 2.2.3 on 2019-07-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allcards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocked_in', models.DateTimeField()),
                ('clocked_out', models.DateTimeField()),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris.Employee')),
            ],
        ),
    ]
