# Generated by Django 2.2.3 on 2019-07-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hris', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allcards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocked_in', models.DateTimeField()),
                ('clocked_out', models.DateTimeField()),
                ('out_date', models.DateField(blank=True, default='', null=True)),
                ('in_date', models.DateField(blank=True, default='', null=True)),
                ('worked_hours', models.DecimalField(decimal_places=5, default='0', max_digits=16)),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris.Employee')),
            ],
        ),
    ]
