# Generated by Django 2.2.3 on 2019-07-22 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hris', '0002_auto_20190722_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_period', models.IntegerField()),
                ('ei_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('cpp_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('qpip_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('wcb_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('cnt_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('hsf_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('vac_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('pmtf_er', models.DecimalField(decimal_places=5, max_digits=16)),
                ('ei_ee', models.DecimalField(decimal_places=5, max_digits=16)),
                ('cpp_ee', models.DecimalField(decimal_places=5, max_digits=16)),
                ('qpip_ee', models.DecimalField(decimal_places=5, max_digits=16)),
                ('taxp_ee', models.DecimalField(decimal_places=5, max_digits=16)),
                ('taxf_ee', models.DecimalField(decimal_places=5, max_digits=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris.Employee')),
            ],
        ),
    ]
