# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Paycal',
            name='earning_pp',
            field=models.DecimalField(decimal_places=5, max_digits=16)
        ),
    ]
