# Generated by Django 2.2.3 on 2019-07-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter employee's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Enter employee's last name", max_length=50)),
                ('birthdate', models.DateField()),
                ('sin_number', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('employee_number', models.IntegerField()),
                ('hire_date', models.DateField()),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'birthdate'],
            },
        ),
    ]
