# Generated by Django 2.2.3 on 2019-07-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=' ', help_text="Enter employee's address", max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='post_code',
            field=models.CharField(default=' ', help_text="Enter employee's postal code", max_length=7),
        ),
        migrations.AddField(
            model_name='employee',
            name='street_name',
            field=models.CharField(default=' ', help_text="Enter employee's address", max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='street_no',
            field=models.CharField(default=' ', help_text="Enter employee's address", max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=5, max_digits=16),
        ),
    ]
